### PR TITLE
Add shouldBoldLastButton config option

### PR DESCRIPTION
**Pull request by ttargo1**
When true, the third button in the modal will have a more prominent style.

### CODE REVIEW

**Comment by jlyman** [comment]
Thanks @ttargo1, that makes things much more explicit and less magical.

For now, the `cancel` style only affects iOS. Would you add a line to the README docs about `shouldBoldLastButton` to the effect of "(currently only modifies iOS styling)" or something similar?

**Comment by ttargo1** [comment]
@jlyman updated 👍

**Comment by ttargo1** [comment]
@jlyman, anything more you'd like added?

**Comment by jlyman** [comment]
Nope, sorry, just got sidetracked. Thanks for following up. I'll merge and push out a release.

**Comment by jlyman** [comment]
Pushed! v3.1.0

**Pull request merged**
