### PR TITLE
User decision callback

### PR DESCRIPTION
**Pull request by sercanov**
Added a callback to handlePositiveEvent function, which will take 2 parameters. First one, 'Is rating requested'; second one 'User decision'

### CODE REVIEW

**Comment by jlyman** [comment]
Thanks for the PR @sercanov. Two things:

1. If a callback isn't supplied, then it's going to throw an error. If we go with this, it should check to see if one was supplied and supply a noop if not, but that leads to point 2.
2. Current convention in the component is to supply additional arguments on construction in the `options` object, instead of on call. I could see this going either way, but if you can potentially call multiple `handlePositiveEvents()` in various parts of your application then you'll have to supply the callback multiple times as well. Thoughts?

Point 1 has to be addressed before it can be merged. Point 2 would be a great point of discussion, would love to have your thoughts on it.

**Comment by sercanov** [comment]
@jlyman I see your concerns and I'm absolutely agree with you, when I made the PR I was desperately needed the callbacks, little selfishness ^^

Before all, are we really need that callback? The purpose I asked for it was analytics purposes. If we are going to include it, we need to think about users who are not going to use callback. So we could consider a second `handlePositiveEventsWithCallback`  function maybe. Or as you said, we could check if there is a callback in the function. I don't think pointing it in the options object will be useful though.

**Comment by jlyman** [comment]
I can certainly see it being useful in different situations, like the analytics scenario you mentioned. I like the idea of passing in an optional callback, and if none is passed in substituting a noop for it. So in the end, it might end up looking like this:

```
async handlePositiveEvent(callback) {
    callback = callback || function () {}
    ...
}
```

One liner change to the PR you have (it would also be nice if you'd update the documentation and comments too, if you have the chance) and it would add some pretty easy flexibility in there.

**Comment by sercanov** [comment]
@jlyman I think it's best way to do it so, made a pair of changes. Will you please check it before merging.

**Comment by jlyman** [comment]
Looks great @sercanov, thank you!

**Pull request merged**
